name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Use variables
        run: |
          echo "docker user variable : $DOCKER_USER"
          echo "docker login variable : $DOCKER_LOGIN"
        env:
          DOCKER_LOGIN: ${{ vars.DOCKER_USER}}
          DOCKER_USER: ${{ vars.DOCKER_USER}}
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.19

      - name: Check out code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Test
        run: make test

      - name: Package
        run: make package

      - name: Docker push
        env:
          DOCKER_LOGIN: ${{ vars.DOCKER_LOGIN }}
          DOCKER_USER: ${{ vars.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: ./scripts/docker-push.sh
